### ISSUE TITLE
[ctcdecode/src/scorer.cpp:57] FATAL: "(access(filename, 0)) == (0)" check failed. Invalid language model path

### ISSUE THREAD

**Issue by sscaptain** [dgaddy/silent_speech#3]
when I run this command in colab : python recognition_model.py --evaluate_saved "./models/recognition_model/model.pt",
it reported the error : [ctcdecode/src/scorer.cpp:57] FATAL: "(access(filename, 0)) == (0)" check failed. Invalid language model path;
I can`t find any about this error.

**Comment by Mannix-D** [comment]
This issue can be solved by download the "lm.binary" file. The links:https://github.com/mozilla/DeepSpeech/releases/download/v0.6.1/lm.binary
