### ISSUE TITLE
Why does recognition_model.py have the error ValueError: one or more references are empty strings?

### ISSUE THREAD

**Issue by kenny881010** [dgaddy/silent_speech#5]
when I run this command  : python recognition_model.py --output_directory "./models/recognition_model/"
it reported the error : raise ValueError("one or more references are empty strings"), ValueError: one or more references are empty strings
![螢幕擷取畫面 2024-01-02 120049](https://github.com/dgaddy/silent_speech/assets/141251893/333a017b-be80-4d0f-85dc-96b236bb3aaa)

**Comment by dgaddy** [comment]
I think that this error comes from using a newer version of the library jiwer that is incompatible with the code.  Try using jiwer version 2.2.1.
